apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi7
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi7/ubi:latest
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
